name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-22.04  # Change the runner version

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or '18' or whichever version you're using

      - name: Install dependencies
        run: npm ci  # Use npm ci for a clean install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Check permissions
        run: ls -la node_modules/.bin  # Check permissions of binaries

      - name: Check Playwright Binary
        run: ls -la node_modules/.bin/playwright  # Check specific permissions

      - name: Run tests
        run: npx playwright test
